Personal Item: Serendipity Bluewing's Plushie
Sector-Umbra/Sector-Umbra pull request #127
Opened 2024-08-30 08:58 UTC by Coolsurf6

## About the PR
Added a personal item for 'Serendipity Bluewing' for VividWisp

## Why / Balance
Personal Item.

## Technical details
Added new YML code using the base moth plushie item. Reused the asset of the mothroach for the headslot  so the plushie can be placed on a players head. 

## Media

![Screenshot_20240830_184331](https://github.com/user-attachments/assets/81887b59-10a8-474e-bc2a-318cf056a140)

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Added Serendipity Bluewing's plushie. Place on head included!

2024-08-30 08:58 UTC, Coolsurf6 commented
Can someone please check the meta data for Copyright? There is use of the mothroach image that was edited, and I want to confirm how to add this to the copyright if it is necessary!

2024-08-30 09:30 UTC, Coolsurf6 commented
Publishing this now. Unsure where to add copyright as VividWisp did the art editing for the mothroach equipped-HELMET file.

2024-08-30 09:39 UTC, lunarcomets commented
if you mean how to add extra copyright to it or something, here’s how the job icons do their copyright (which uses multiple sources and authors for the sprites)

https://github.com/Sector-Umbra/Sector-Umbra/blob/master/Resources/Textures/Interface/Misc/job_icons.rsi/meta.json

2024-08-30 09:51 UTC, Coolsurf6 commented
> if you mean how to add extra copyright to it or something, here’s how the job icons do their copyright (which uses multiple sources and authors for the sprites)
> 
> https://github.com/Sector-Umbra/Sector-Umbra/blob/master/Resources/Textures/Interface/Misc/job_icons.rsi/meta.json

Ahh I see how to separate it, my issue is just... finding the original file attributes for the 0-equipped-HELMET.png for the mothroach.

2024-08-30 22:18 UTC, Coolsurf6 commented on Resources/Textures/_Umbra/Objects/Fun/Toys/plushie_serendipity.rsi/meta.json
> +    "copyright": "plushie_seren modified by Necroa from plushie_moth.png from commit: https://github.com/Sector-Umbra/Sector-Umbra/commit/b50e5651a19ccf2e5300b63ab896251b67820a1f.",
I've fixed the plushie_serendipity but I have NO idea where to find the copyright of the mothroach equipped image. 

I thought I had found it from something on fulpstation but the github page so some help would be greatly appreciated!

2024-08-30 22:23 UTC, Coolsurf6 commented on Resources/Textures/_Umbra/Objects/Fun/Toys/plushie_serendipity.rsi/meta.json
> +    "copyright": "plushie_seren modified by Necroa from plushie_moth.png from commit: https://github.com/Sector-Umbra/Sector-Umbra/commit/b50e5651a19ccf2e5300b63ab896251b67820a1f.",
It was based off the lizard plushie with reference of the mothroach version I am just hearing. Should be able to put the lizard one in.

2024-08-30 22:25 UTC, Coolsurf6 commented on Resources/Textures/_Umbra/Objects/Fun/Toys/plushie_serendipity.rsi/meta.json
> +    "copyright": "plushie_seren modified by Necroa from plushie_moth.png from commit: https://github.com/Sector-Umbra/Sector-Umbra/commit/b50e5651a19ccf2e5300b63ab896251b67820a1f.",
I have just added it on a935652. See if that works.

2024-08-31 06:45 UTC, TsjipTsjip requested changes

2024-08-31 06:45 UTC, TsjipTsjip commented on Resources/Textures/_Umbra/Objects/Fun/Toys/plushie_serendipity.rsi/meta.json
> +    "copyright": "plushie_serendipity modified by Necroa from plushie_moth.png from commit: https://github.com/Sector-Umbra/Sector-Umbra/commit/b50e5651a19ccf2e5300b63ab896251b67820a1f. serendipity-e
This copyright line does not make sense to me.

Format is: sprite_state modified by author_identification from (sprite_state from) commit commit_url

It does not matter where the commit URL comes from so long as that commit's artwork is CC-BY-SA-3.0 or CC-BY-NC-SA-3.0. If the commit comes from Sector Umbra, that is automatically the case. You still need that URL though.

2024-08-31 06:46 UTC, TsjipTsjip commented on Resources/Textures/_Umbra/Objects/Fun/Toys/plushie_serendipity.rsi/meta.json
> +    "copyright": "plushie_serendipity modified by Necroa from plushie_moth.png from commit: https://github.com/Sector-Umbra/Sector-Umbra/commit/b50e5651a19ccf2e5300b63ab896251b67820a1f. serendipity-e
Nevermind I am an idiot, please continue.

2024-08-31 06:46 UTC, TsjipTsjip approved these changes
GM approval.

2024-09-01 00:36 UTC, Coolsurf6 commented on Resources/Prototypes/_Umbra/Entities/Objects/Fun/toys.yml
> +  parent: BasePlushie
Oh whoops! 

This probably was because it was the first time making a new plushie and I just reused code. If making the parent the MothPlushie doesn't cause issues please change it over please!

2024-09-01 00:39 UTC, Coolsurf6 commented on Resources/Prototypes/_Umbra/Entities/Objects/Fun/toys.yml
> +  parent: BasePlushie
Is that alright if you can change it over or do I need to via my branch? I think I have it selected that Collaborators have access to my branch.

2024-09-01 01:17 UTC, merged