Change Several Roletimers
Sector-Umbra/Sector-Umbra pull request #13
Opened 2024-04-16 02:52 UTC by luckyshotpictures

## About the PR

This changes most command roles to be three hours of overall playtime, and warden to one hour.

## Why / Balance

It was discussed in GM chat, that it is not desireable, to have new players play command roles immediately, and to let them play a shift before commiting to command.

## Technical details

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

2024-04-16 06:21 UTC, Simyon264 requested changes

2024-04-16 06:21 UTC, Simyon264 commented on Resources/Prototypes/Roles/Jobs/Command/captain.yml
> +      time: 10800 # 3 hours
```suggestion
    - !type:OverallPlaytimeRequirement
      time: 10800 # 3 hours
```

2024-04-16 06:21 UTC, Simyon264 commented on Resources/Prototypes/Roles/Jobs/Command/centcom_official.yml
> -    pocket2: PenCentcom
This has nothing to do with role timers. Why is this change in this PR?

2024-04-16 06:21 UTC, Simyon264 commented on Resources/Prototypes/Roles/Jobs/Command/head_of_personnel.yml
> +      time: 10800 # 3 hours
```suggestion
    - !type:OverallPlaytimeRequirement
      time: 10800 # 3 hours
```

2024-04-16 06:21 UTC, Simyon264 commented on Resources/Prototypes/Roles/Jobs/Science/research_director.yml
>      - !type:DepartmentTimeRequirement
```suggestion

```

2024-04-16 06:22 UTC, Simyon264 commented on Resources/Prototypes/Roles/Jobs/Science/research_director.yml
>      - !type:DepartmentTimeRequirement
You removed the playtime requirements for the department but left in the type for it.

2024-04-16 06:49 UTC, TsjipTsjip commented on Resources/Prototypes/Roles/Jobs/Security/warden.yml
>      - !type:RoleTimeRequirement
`- !type:OverallPlaytimeRequirement`

2024-04-16 15:57 UTC, Simyon264 approved these changes
YAML LGTM

2024-04-18 13:21 UTC, TsjipTsjip commented on Resources/Prototypes/Roles/Jobs/Command/centcom_official.yml
> -    pocket2: PenCentcom
Change is too minor to be atomized into its own PR at this time.

2024-04-18 13:33 UTC, merged