Personal Item: Michael's Card
Sector-Umbra/Sector-Umbra pull request #137
Opened 2024-09-12 11:55 UTC by AemonTillado

## About the PR
This PR adds a personal item for Michael Hands - a Father's Day card gifted to him by his son.

## Why / Balance
Allows Michael to spawn with this sentimental item which he currently prints from a fax machine at the start of every shift.

## Technical details
The card is parented from in-game books, and the sprite is based on the default cover_base book sprite. It has been altered to be edible in the same manner of paper, only with double the waiting time and providing three fiber instead of one (to represent consuming an entire cardboard rectangle as opposed to a single sheet of paper!)

## Media
![card1](https://github.com/user-attachments/assets/fbccb21d-4119-458e-bc91-83afed15d4a9)
![card2](https://github.com/user-attachments/assets/33f8eac2-6a95-476e-8072-e59226ce4b28)
![card3](https://github.com/user-attachments/assets/6c4ffea9-a733-4e2b-8a42-72721abcf631)
![card4](https://github.com/user-attachments/assets/98202074-f209-430c-b9dd-363fd4b8026d)
![card5](https://github.com/user-attachments/assets/cdd86c3e-c682-4c13-9f38-14d27ca0e792)

## Requirements

- [X] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- add: Personal item for Michael Hands - Michael's Card.

2024-09-12 11:57 UTC, Coolsurf6 commented
: )

2024-09-12 16:52 UTC, TsjipTsjip requested changes
One issue needs to be addressed (caused by personal items rules). I am deciding to allow the extended eating delay for the reason provided by the PR author.

GM approval when review is addressed.

2024-09-12 16:52 UTC, TsjipTsjip commented on Resources/Prototypes/_Umbra/Entities/Objects/Misc/Books/michaels_card.yml
> +          Quantity: 3
Remove the SolutionContainerManager component, this should not be modified from the base item.

2024-09-13 14:57 UTC, TsjipTsjip commented on Resources/Prototypes/_Umbra/Entities/Objects/Misc/Books/michaels_card.yml
> +          Quantity: 3
Well that's just SS14 scrunkliness for you isn't it... Fine. Accepted as-is.

2024-09-13 14:57 UTC, TsjipTsjip approved these changes

2024-09-13 14:57 UTC, merged