Add Yarna Armoured Coat
Sector-Umbra/Sector-Umbra pull request #19
Opened 2024-04-22 12:55 UTC by Frostbitey

## About the PR
Added the Yarna's Armoured Coat!

## Why / Balance
As a personal item for Yarna-Crimson, Aka. OverwatchVoice
The Yarna's Amoured Coat has all armor statistics as the Warden's Armoured Winter Coat

## Media
Preview:
![image](https://github.com/Sector-Umbra/Sector-Umbra/assets/42723925/c8b5aa4b-fade-4532-abfc-0428d04e9360)
![image](https://github.com/Sector-Umbra/Sector-Umbra/assets/42723925/e1e3db08-97af-4eb0-8d0b-7efec2427718)
![image](https://github.com/Sector-Umbra/Sector-Umbra/assets/42723925/b075ff87-83e0-4ffa-99be-d7c9e8dc30ba)
![image](https://github.com/Sector-Umbra/Sector-Umbra/assets/42723925/ddbacb68-66a8-4cc8-a7bc-3bf991ec7124)

**Changelog**

:cl:
- add: Added Yarna's Armoured Coat!!

2024-04-22 13:00 UTC, TsjipTsjip requested changes

2024-04-22 13:00 UTC, TsjipTsjip commented on Resources/Prototypes/_Umbra/Entities/Clothing/OuterClothing/coats.yml
> +        Heat: 0.70
Not allowed in a personal item (inherit from a warden's coat instead).

2024-04-22 13:00 UTC, TsjipTsjip commented on Resources/Prototypes/_Umbra/Entities/Clothing/OuterClothing/coats.yml
> +    damageCoefficient: 0.90
Not allowed in a personal item (inherit from a warden's coat instead).

2024-04-22 15:08 UTC, Frostbitey commented on Resources/Prototypes/_Umbra/Entities/Clothing/OuterClothing/coats.yml
> +  suffix: PersonalItem
Problems Fixed

2024-04-22 15:08 UTC, Frostbitey commented on Resources/Prototypes/_Umbra/Entities/Clothing/OuterClothing/coats.yml
> +    damageCoefficient: 0.90
Problems FIxed

2024-04-24 06:44 UTC, TsjipTsjip approved these changes
This only conveys a GM approval for the concept of the item, and not of the item actually in the game, as I have not been able to test it in-game yet. YML looks good tho.

2024-04-27 18:26 UTC, TsjipTsjip approved these changes
Works after local testing. Good to merge.

2024-04-27 18:27 UTC, merged