Add Mile's Flower Braid
Sector-Umbra/Sector-Umbra pull request #20
Opened 2024-04-24 05:08 UTC by FlannelVioiln

## About the PR
Added Mile's Flower Braid.

## Why / Balance
Wanted to add a personal item for Georgia A Miles into umbra

## Technical details
just added some pngs

## Media
![image](https://github.com/Sector-Umbra/Sector-Umbra/assets/83882749/bc3b04ab-ad9b-4d69-ab8a-51c023658862)
![image](https://github.com/Sector-Umbra/Sector-Umbra/assets/83882749/17cfda8a-9738-4a4f-8533-603c7a28ebd4)
![image](https://github.com/Sector-Umbra/Sector-Umbra/assets/83882749/db4637ec-4391-4bb6-b3fe-b307877d93a7)
![image](https://github.com/Sector-Umbra/Sector-Umbra/assets/83882749/380c2a5e-3c57-4ca6-bc2f-e9bdb880cf76)
![image](https://github.com/Sector-Umbra/Sector-Umbra/assets/83882749/641926ed-0a12-4a34-95fa-bcf41eeaec09)

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
none

**Changelog**
:cl:
- add: Added Mile's Flower Braid

2024-04-24 06:27 UTC, Tych0theSynth commented
You can't add this directly into the master files/directories I'm afraid. They'll need to go in our specific _Umbra directories.
The sprites will need to go into:
/Textures/_Umbra/Clothing/Head

and YAML will need to go into (you will need to create it front scratch):
/Prototypes/_Umbra/Entities/Clothing/Head

(You will need to create the head/hats directory if it doesn't exist yet)

2024-04-24 06:43 UTC, TsjipTsjip requested changes
Minor remarks, see also Tych0's remark above. If needed we can walk you through this.

2024-04-24 06:43 UTC, TsjipTsjip commented on Resources/Prototypes/Entities/Clothing/Head/misc.yml
> +
Please add a `suffix: PersonalItem` line, so we can easily identify these from other items.

2024-04-24 21:24 UTC, FlannelVioiln commented
> You can't add this directly into the master files/directories I'm afraid. They'll need to go in our specific _Umbra directories. The sprites will need to go into: /Textures/_Umbra/Clothing/Head
> 
> and YAML will need to go into (you will need to create it front scratch): /Prototypes/_Umbra/Entities/Clothing/Head
> 
> (You will need to create the head/hats directory if it doesn't exist yet)

ive created the new directory and moved everything around, but now the sprint is very broken. Am I suppoesd to add a reference somewhere that I'm missing

2024-04-24 21:29 UTC, Tych0theSynth commented
> > You can't add this directly into the master files/directories I'm afraid. They'll need to go in our specific _Umbra directories. The sprites will need to go into: /Textures/_Umbra/Clothing/Head
> > and YAML will need to go into (you will need to create it front scratch): /Prototypes/_Umbra/Entities/Clothing/Head
> > (You will need to create the head/hats directory if it doesn't exist yet)
> 
> ive created the new directory and moved everything around, but now the sprint is very broken. Am I suppoesd to add a reference somewhere that I'm missing

Have you checked the meta.json for the sprites to make sure that's correct, and that the files are looking for the sprites via the correct path?

2024-04-24 21:32 UTC, arimah commented
> ive created the new directory and moved everything around, but now the sprint is very broken. Am I suppoesd to add a reference somewhere that I'm missing

You don't appear to have pushed the edited code, so I can't comment on that directly. Make sure that the paths on the `Sprite` and `Clothing` components refer to the correct location, including `_Umbra/` as appropriate. You can always look at other personal items as examples. :)

2024-04-24 21:46 UTC, FlannelVioiln commented
> > > You can't add this directly into the master files/directories I'm afraid. They'll need to go in our specific _Umbra directories. The sprites will need to go into: /Textures/_Umbra/Clothing/Head
> > > and YAML will need to go into (you will need to create it front scratch): /Prototypes/_Umbra/Entities/Clothing/Head
> > > (You will need to create the head/hats directory if it doesn't exist yet)
> > 
> > 
> > ive created the new directory and moved everything around, but now the sprint is very broken. Am I suppoesd to add a reference somewhere that I'm missing
> 
> Have you checked the meta.json for the sprites to make sure that's correct, and that the files are looking for the sprites via the correct path?

turns out i had the extra an extra /misc/ in the path referenced in the yml. all good and building now.

2024-04-24 21:52 UTC, arimah requested changes

2024-04-24 21:52 UTC, arimah commented on Resources/Textures/Clothing/Head/Misc/georgia-flower-braid.rsi/meta.json
> +{
Remove the entire Resources/Textures/Clothing/Head/Misc/georgia-flower-braid.rsi directory, including this file and the sprites in it. The others are in the right place. :) Don't forget to `git add` removals!

2024-04-24 23:14 UTC, FlannelVioiln commented on Resources/Textures/Clothing/Head/Misc/georgia-flower-braid.rsi/meta.json
> +{
done!

2024-04-25 05:48 UTC, TsjipTsjip approved these changes
GM approval. Files also look good.

2024-04-25 08:18 UTC, arimah approved these changes

2024-04-25 08:21 UTC, merged