Personal Item: Attacus Fischer's Guitar
Sector-Umbra/Sector-Umbra pull request #203
Opened 2024-11-17 07:32 UTC by Coolsurf6

## About the PR
Added a personal item for 'Attacus Fischer' for JustLeoHonestly

## Why / Balance
Personal Item.

## Technical details
Added new YML code based off the AcousticGuitarInstrument. I have also added a Jazz midi sounds using sound midi program 26.

## Media

![Screenshot_20241117_171454](https://github.com/user-attachments/assets/71dce15e-b19f-4918-9390-30e908cfed43)

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Added Attacus Fischer's Guitar. Red this time!

2024-11-17 07:36 UTC, Coolsurf6 commented
Baller

2024-11-17 08:50 UTC, TsjipTsjip approved these changes
GM approval. (Resprite rule)

2024-11-19 21:10 UTC, PursuitInAshes submitted a review, later dismissed
Works in game but please address the other comments here.

2024-11-19 21:10 UTC, PursuitInAshes commented on Resources/Prototypes/_Umbra/Entities/Objects/Fun/Instruments/instruments_string.yml
> +- type: entity
Convention says you include the player name and character name at the start of this item. Refer to seren's guitar PR for an example.

2024-11-19 21:10 UTC, PursuitInAshes commented on Resources/Textures/_Umbra/Objects/Fun/Instruments/attacusguitar.rsi/meta.json
> +  "copyright": "https://github.com/vgstation-coders/vgstation13 at 8d9c91e19cb52713c7f7f1804c2b6f7203f8d331, equipped backpack by ;3#1161",
Is this copyright accurate?

2024-11-20 23:42 UTC, Coolsurf6 commented on Resources/Prototypes/_Umbra/Entities/Objects/Fun/Instruments/instruments_string.yml
> +- type: entity
Will get this done ASAP. Not sure how I missed this.

2024-11-21 08:51 UTC, Coolsurf6 commented on Resources/Prototypes/_Umbra/Entities/Objects/Fun/Instruments/instruments_string.yml
> +- type: entity
Resolved with the same player comment as the Ace Bluewing's Guitar PR.

2024-11-21 10:55 UTC, TsjipTsjip requested changes

2024-11-21 10:55 UTC, TsjipTsjip commented on Resources/Textures/_Umbra/Objects/Fun/Instruments/attacusguitar.rsi/meta.json
> +  "copyright": "wielded-inhand-right/left, inhand-right/left, icon, and equipped-SUITSTORAGE/BACKPACK modified by VividWisp from commit: https://github.com/space-wizards/space-station-14/commit/ae41d
See also Ace Bluewing's guitar.

I cannot find the original guitar sprite on this commit.

2024-11-21 13:06 UTC, Coolsurf6 commented on Resources/Textures/_Umbra/Objects/Fun/Instruments/attacusguitar.rsi/meta.json
> +  "copyright": "wielded-inhand-right/left, inhand-right/left, icon, and equipped-SUITSTORAGE/BACKPACK modified by VividWisp from commit: https://github.com/space-wizards/space-station-14/commit/ae41d
Check the Ace Bluewing's PR for the changes for this.

2024-11-22 13:41 UTC, TsjipTsjip approved these changes

2024-11-22 13:41 UTC, merged