Prevents rat king from spawning, makes rat king team antag
Sector-Umbra/Sector-Umbra pull request #208
Opened 2024-11-17 19:09 UTC by Boaz1111

## About the PR

Rat king no longer spawns naturally and it's a team antag now
## Why / Balance

Requested by Tsjip
## Technical details

## Media

![image](https://github.com/user-attachments/assets/6f05cbee-acee-4ddb-8aa1-aeb8bb9d6648)

## Requirements

- [X ] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [ X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

2024-11-19 21:13 UTC, PursuitInAshes commented on Resources/Locale/en-US/ghost/roles/ghost-role-component.ftl
> +ghost-role-information-rat-king-rules = You are a [color=red][bold]Team Antagonist[/bold][/color] with all other rat kings.
This is not a proper review, I will leave that to Tsjip, however it might be good to explain what Team Antagonist means in this context. Just a little blurb like " Work with other rat kings to complete your goals." or something.

2024-11-21 10:49 UTC, TsjipTsjip requested changes
Gonna actually work out the rules issue in a separate PR myself. These changes can be dropped.

Additionally, the actual problem is the `BasicAntagEventsTable` being called, which I should have disabled prior... Can you look into why this table is still being used by the event schedulers?

2024-11-22 19:05 UTC, Boaz1111 commented
Sure!

2024-12-06 13:59 UTC, TsjipTsjip commented
@Boaz1111 Are you coming back to this?

2024-12-06 14:28 UTC, Boaz1111 commented
I looked at why the table was still being called, I can't find any reasons it would be

2024-12-14 09:20 UTC, closed without merging

2024-12-14 09:20 UTC, TsjipTsjip commented
In that case this needs a more thorough investigation as to why this is happening. I'll close the PR for now, we'll work on this at a later time.