Personal item: Old space lizard plushie
Sector-Umbra/Sector-Umbra pull request #211
Opened 2024-11-20 20:15 UTC by nkokic

## About the PR
Added a personal item for 'Darting Groth'

## Why / Balance
Personal Item.

## Technical details
Added new YML code using the space lizard plushie item.
Plushie is wearable as helmet clothing and has inhand sprites.

## Media

## Requirements
- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [ ] I have added media to this PR or it does not require an ingame 

## Breaking changes
N/A

**Changelog**

🆑
- add: Added Darting Groth's old space lizard plushie. Feels very lucky.
`

2024-11-20 22:09 UTC, nkokic commented
Copyright in meta.json in rsi might be incorrect.
Not sure what to link or how to find appropriate one.

2024-11-21 10:58 UTC, TsjipTsjip requested changes
Looks good, GM approval for the item is given. Can be merged when tested in game, verified to be working and the below comment is addressed.

2024-11-21 10:58 UTC, TsjipTsjip commented on Resources/Textures/_Umbra/Objects/Fun/Toys/plushie_old_space_lizard.rsi/meta.json
> +    "copyright": "Dart111 modified OldPlushieSpaceLizard icon from PlushieSpaceLizard, head and inhand sprites made by Nikovnik (github: nkokic)",
Needs a commit reference for the purposes of source permanence.

2024-11-22 16:16 UTC, nkokic commented on Resources/Textures/_Umbra/Objects/Fun/Toys/plushie_old_space_lizard.rsi/meta.json
> +    "copyright": "Dart111 modified OldPlushieSpaceLizard icon from PlushieSpaceLizard, head and inhand sprites made by Nikovnik (github: nkokic)",
Found out hot to search around the repository and to do "git blame".
Modified it and I think it should be fine now.

2024-11-22 16:29 UTC, TsjipTsjip approved these changes

2024-11-22 16:29 UTC, merged