Upstream merge (11/28/24)
Sector-Umbra/Sector-Umbra pull request #223
Opened 2024-11-28 23:13 UTC by PursuitInAshes

## About the PR
Merges wizden stable up to 11/28/24.
Merges the following CD PRs:

Merges https://github.com/cosmatic-drift-14/cosmatic-drift/pull/467
Merges https://github.com/cosmatic-drift-14/cosmatic-drift/pull/471
Merges https://github.com/cosmatic-drift-14/cosmatic-drift/pull/472
Merges https://github.com/cosmatic-drift-14/cosmatic-drift/pull/477
Merges https://github.com/cosmatic-drift-14/cosmatic-drift/pull/485
Merges https://github.com/cosmatic-drift-14/cosmatic-drift/pull/478
https://github.com/cosmatic-drift-14/cosmatic-drift/pull/484
https://github.com/cosmatic-drift-14/cosmatic-drift/pull/487

Reverts Umbra PR b770e0a

The revert of that commit and merge of 471 is simple code clean up.

2024-11-28 23:58 UTC, OctoRocket requested changes

2024-11-28 23:58 UTC, OctoRocket commented on Content.Server/StationEvents/Events/IonStormRule.cs
Seems to have partially reverted with the merge

2024-11-29 00:10 UTC, OctoRocket commented on Content.Server/StationEvents/Events/IonStormRule.cs
Misread that, it actually is just using features that are no longer included in the file

2024-11-29 00:19 UTC, OctoRocket approved these changes

2024-11-29 00:29 UTC, OctoRocket commented
`Failed!  - Failed:    54, Passed:     5, Skipped:     0, Total:    59, Duration: 4 s - Content.IntegrationTests.dll (net8.0)`

Seems like the tests really like this one

2024-11-29 00:45 UTC, OctoRocket commented
The test fails were fixed 2 weeks ago in Robust Toolbox's netserializer, seems like the latest Robust Toolkit version was just not pulled.

2024-11-29 10:15 UTC, TsjipTsjip approved these changes
Works on Coolsurf6's machine

2024-11-29 10:15 UTC, merged

2024-11-29 10:15 UTC, Coolsurf6 commented
*grins