Nurse PDA, Skirt of Life, Alt Nurse Hat
Sector-Umbra/Sector-Umbra pull request #233
Opened 2024-12-08 16:30 UTC by PursuitInAshes

## About the PR
Revives #109 .

Adds the Skirt of Life and a recolored Nurse Hat to the Medical Doctor loadout options.
Adds a new PDA, the Nurse PDA, which uses CD's job title system.

## Why / Balance
More RP options for medical staff.

## Technical details
N/A - YAML

## TODO
Make the PDA Icon load

2024-12-09 20:09 UTC, PursuitInAshes commented
So it turns out putting the sprite in the upstream folder (and adjusting the yaml), makes the sprite load just fine. I'll take a look at the file path again because thats my best guess.

2024-12-19 18:15 UTC, PursuitInAshes commented
I'll come back to fix this later, the changes are done, I just have to rebase properly instead of whatever I did.

2024-12-19 22:09 UTC, PursuitInAshes commented
Just confirmed that it still works ingame, this is ready for review.

2024-12-28 01:11 UTC, Coolsurf6 requested changes
Everything aside from a comment seems fine and runs in game well.

2024-12-28 01:11 UTC, Coolsurf6 commented on Resources/Prototypes/Loadouts/loadout_groups.yml
> +  - NurseHatAlt #Umbra
Just a space needed to make # Umbra to remain consistent.

2024-12-28 10:26 UTC, Coolsurf6 approved these changes
Change is done, looks good.

2024-12-28 10:35 UTC, merged