Make APCs explode (when turned on) after a random delay during a power grid check.
Sector-Umbra/Sector-Umbra pull request #24
Opened 2024-04-27 12:35 UTC by Simyon264

## About the PR

Was mentioned that admins already do this manually. This PR just enforces this mechanically.

## Technical details

Adds a system which makes device explode when in a overloaded state. This can be adapted to be used for other devices which are not APCs.

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase
https://cdn.discordapp.com/attachments/1208920487267143711/1233757174031974410/Desktop_2024.04.27_-_14.28.14.03.mp4?ex=662e4168&is=662cefe8&hm=a5e47fa93679acb2992f4a86afd41ee1c023a3919cb6f275798beb252d493f4f&

**Changelog**

:cl: Simyon
- tweak: APCs will now explode during a power grid check when they are turned on.

2024-04-27 18:37 UTC, TsjipTsjip requested changes
Not tested in-game just yet, but the chat message showing up in the chatbox, along with the frequency of the buzzing, makes it quite annoying. Could you tone down the buzzing and look at how vendors send their advertisements? Those also don't appear in chat windows.

2024-04-27 18:37 UTC, TsjipTsjip commented on Resources/Locale/en-US/power/overload.ftl
> +﻿electrical-overload-system-buzz = buzzes loudly
`buzzes loudly` -> `buzzes`

2024-04-27 19:52 UTC, Simyon264 commented on Resources/Locale/en-US/power/overload.ftl
> +﻿electrical-overload-system-buzz = buzzes loudly
Done.

2024-04-28 11:00 UTC, arimah requested changes

2024-04-28 11:13 UTC, TsjipTsjip commented on Resources/Locale/en-US/power/overload.ftl
> +﻿electrical-overload-system-buzz = buzzes
I did already request this to be changed from `buzzes loudly`. :p

Can workshop it if it happens again. Currently we already have a sort of standing fact that "Electrical stuff buzzing = Bad" through manual interactions, so I believe this is sufficient for now.

2024-04-28 11:19 UTC, arimah commented on Resources/Locale/en-US/power/overload.ftl
> +﻿electrical-overload-system-buzz = buzzes
Oh, I'm sorry! I missed that! I suppose we'll just keep it as "buzzes" and see what happens.

2024-04-28 11:32 UTC, arimah approved these changes
Works as intended, code looks fine. I'm happy with it. :)

2024-04-28 11:33 UTC, TsjipTsjip approved these changes

2024-04-28 11:33 UTC, merged