Metabolizing bloodstream and blood pressure
Sector-Umbra/Sector-Umbra pull request #241
Opened 2024-12-12 21:52 UTC by nkokic

## About the PR

Bloodstream now acts as metabolizing solution.
Changed blood loss damage scaling to be linear. Having blood loss now does double asphyxiation instead.
Added hypervolemia damage which causes minor slash with bleeding effect and asphyxiation.
Hypervolemia damage scales similarly with blood loss after HyperVolemiaThreshold in opposite direction.

## Why / Balance

To increase medical immersion, punish reckless chemical dumping and make gluttony an actual concern.
Having disrupted blood level is now a bigger concern and its not something to shrug off.

## Technical details

Mainly edited BloodstreamSystem and BloodstreamComponent to implement hypervolemia similarly to how blood loss is implemented.
Changed wherever DefaultChemicalsSolutionName was used in context of transferring chemicals or metabolizing, DefaultBloodSolutionName was put instead.
Due to how BloodstreamSystem treats BloodMaxVolume differently, I have changed its name to BloodReferenceVolume because it does not mean maximum volume anymore. (in C# and YAML files)
Maximum bloodstream solution is double of BloodReferenceVolume.
Blood level is calculated by bloodsolution FillFraction times 2.
Made sure that charcoal's cleansing of chemicals does not flush blood reagents.
Made sure rejuvenating removes everything from bloodstream and then refills it with right amount of blood.
Saline also has been also turned down to be equal with blood.

## Media

How hypervolemia looks on scanner and what's under the car hood:
![image](https://github.com/user-attachments/assets/f90d867c-a84e-415b-8378-c477212c434e)

Visual representation of damage scaling:
![image](https://github.com/user-attachments/assets/8b7e73e1-cf76-4603-b027-fef07b1e1587)

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

Possible concern: Merges from upstream might throw errors if they mention bloodMaxVolume instead of bloodReferenceVolume.

**Changelog**

:cl:
- add: Added guide entry about blood pressure and it's management
- add: Added hypervolemia damage. Consists of asphyxiation and minor slash.
- tweak: Bloodloss damage is applied linearly. Potentially more dangerous than usually.
- tweak: Changed bloodloss damage to stronger asphyxiation damage only
- tweak: Maximum blood level is now double of healthy blood level
- tweak: Rerouted all chemicals that mob can take into bloodstream instead of chemical solution

2024-12-12 22:04 UTC, PursuitInAshes requested changes
If you could go through and markdown any changes you've made to upstream files as `# Umbra: Whatever change` or `// Umbra: Whatever change` (depending on file format), it would be greatly appreciated.

2024-12-13 07:55 UTC, TsjipTsjip reviewed
With regards to the idea and design: This is awesome. I want this.

With regards to maintainability, code isolation is a concern. I'll review that properly at a later time, though I am not a big fan of renaming maxBloodLevel already. I'll see if I can think of a way to circumvent this.

2024-12-15 16:25 UTC, PursuitInAshes commented
When you undraft this let me know and I'll get a code review done. If you are unsure if something would pass through a review or not, you can ping one of the maints or myself on discord.

2024-12-17 19:42 UTC, nkokic commented
Okay. It's definitely ready now.

2024-12-17 21:21 UTC, deepdarkdepths commented on Resources/ServerInfo/Guidebook/_Umbra/Medical/BloodPressure.xml
> +Blood level bellow [color=#5959FF]90%[/color] ([color=#5959FF]270[/color] units) is considered [color=#5959FF]hypovolemia[/color].
```suggestion
Blood level below [color=#5959FF]90%[/color] ([color=#5959FF]270[/color] units) is considered [color=#5959FF]hypovolemia[/color]. 
```

2024-12-17 21:21 UTC, deepdarkdepths commented on Resources/ServerInfo/Guidebook/_Umbra/Medical/BloodPressure.xml
> +It is important to maintain optimal blood pressure at all times. [color=#59FF59]Normal[/color] healthy humanoid has around [color=#59FF59]300[/color] units of blood
```suggestion
It is important to maintain optimal blood pressure at all times. A [color=#59FF59]normal[/color] healthy humanoid has around [color=#59FF59]300[/color] units of blood
```

2024-12-17 21:21 UTC, deepdarkdepths commented on Resources/ServerInfo/Guidebook/_Umbra/Medical/BloodPressure.xml
> +- Dizyness
```suggestion
- Dizziness
```

2024-12-17 21:21 UTC, deepdarkdepths commented on Resources/ServerInfo/Guidebook/_Umbra/Medical/BloodPressure.xml
> +- Dizzyness
```suggestion
- Dizziness
```

2024-12-17 21:23 UTC, deepdarkdepths commented
Just pointed out some minor typos 👍

2025-01-09 21:53 UTC, nkokic commented
TODO:
[ ] Make BloodstreamSystem method of calculating blood level for health analyzers

2025-01-19 14:34 UTC, nkokic commented
Transferred PR changes to upstream:
https://github.com/space-wizards/space-station-14/pull/34521

2025-01-19 17:50 UTC, PursuitInAshes commented
DNM label is just so wizden can decide what to do with the upstream PR.

If the wizden PR sits for a while (or you feel it won't be looked at) ping me and we can arrange merging it here despite it still being open on wizden's side.

2025-02-14 08:01 UTC, TsjipTsjip commented
Tracking updated to:
- https://github.com/space-wizards/space-station-14/pull/35071
- https://github.com/space-wizards/space-station-14/pull/34976

2025-06-29 16:54 UTC, PursuitInAshes commented
I have notifications on for all of the upstream PRs that this PR is connected to. Once those get merged or closed, we can come back to this one if you are still interested.
If you have any questions, you are free to email me or contact me via discord.

2025-06-29 16:54 UTC, closed without merging