Port Twinpointers from Echo, add them to Maints > Tools > Uncommon spawn table
Sector-Umbra/Sector-Umbra pull request #252
Opened 2024-12-27 15:43 UTC by redmushie

Ported the Twinpointers from https://github.com/echo-station/echo-station/pull/104

## About the PR
- Ported Twinpointers, a box of two pinpointers that point at one another.
- Added them to the Maintance Tools spawner's Uncommon section.

## Why / Balance
Because it's fun! Relatively rare but has great utilitary value.

## Technical details
I had to add one event to intercept the "SpawnOnInteract" functionality, but after that everything is isolated to `_Echo/` folders/packages.

## Media

Skip to 0:20

https://github.com/user-attachments/assets/0c8791a2-3ec3-4db8-90e3-3986fd2d26c5

## Requirements
- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes
Should be zero!

**Changelog**

:cl: redmushie
- add: Added twinpointers, a pair of pinpointers that point at one another
- tweak: Added twinpointer box to maintenance spawns (uncommon)

2024-12-27 15:47 UTC, luckyshotpictures commented
![isthisnormal](https://github.com/user-attachments/assets/89a2e9d6-0614-4d92-8da2-b27c3d08af6e)

2024-12-27 15:48 UTC, Boaz1111 commented
"A box containing a pair of twinpointers. For right when you left your right hand left." I think I just had a serious stroke

2024-12-27 15:51 UTC, redmushie commented
> "A box containing a pair of twinpointers. For right when you left your right hand left." I think I just had a serious stroke

We really tried to make it as confusing and left/right as we could!

2024-12-27 16:03 UTC, PursuitInAshes requested changes
Not a full review, just basic things I saw that would be good to clean up, I'll be able to sit down and look at the C# soon, but remind me if I don't get around to it.

2024-12-27 16:03 UTC, PursuitInAshes commented on Content.Shared/_Echo/Pinpointer/SharedTwinPointerSystem.cs
> +﻿
Extra unneeded line here that can be removed. (Ln 2 or ln 1)

2024-12-27 16:10 UTC, redmushie commented on Resources/Textures/_Echo/Objects/Devices/pinpointer.rsi/meta.json
> +    "copyright": "Taken from tgstation at https://github.com/tgstation/tgstation/commit/59f2a4e10e5ba36033c9734ddebfbbdc6157472d, station and syndicate pinpointer resprited by Ubaser, salvage pinpoin
Guh, I fixed it but then had to redo it. My bad.

2024-12-27 16:10 UTC, redmushie commented on Content.Shared/_Echo/Pinpointer/SharedTwinPointerSystem.cs
> +﻿
I have *no clue* where those came from. Fixed

2024-12-27 16:10 UTC, redmushie commented on Resources/Prototypes/_Echo/Entities/Objects/Devices/twinpointer.yml
> +  parent: [BaseItem]
Fixed

2024-12-30 05:41 UTC, PursuitInAshes commented on Content.Shared/_Echo/Pinpointer/SharedTwinPointerSystem.cs
I already asked in discord but I'm asking here too, just to be sure it doesn't slip through the cracks.

What is the point of this system? Is it required?

2024-12-30 08:37 UTC, redmushie commented
At 00:34 in the video you can see the left pinpointer overlay sprites are offset relative to the base layer. I've offset the base layer by 1px to realign them; it's visually pretty unnoticeable.

2024-12-30 08:38 UTC, redmushie commented on Content.Shared/_Echo/Pinpointer/SharedTwinPointerSystem.cs
Removing it didn't seem to cause any functional or test errors, so I guess it wasn't necessary.

2024-12-30 08:38 UTC, redmushie commented
Test failure unrelated

2024-12-30 17:55 UTC, PursuitInAshes requested changes
I think most of this can be done by subscribing to MapInit and when TwinPointerComponent initializes have it attempt to find the nearest identical component, and then linking them together.

This would be more direct and means you aren't reliant on SpawnItemsOnUse anymore (Along with you not having to make edits to it.)

2025-02-08 18:13 UTC, PursuitInAshes commented
Heya! Just checking in, is there intent to come back to this PR?

2025-02-14 08:00 UTC, TsjipTsjip commented
Closing due to stale, if you wish, you can always reopen this PR so we can further assist you again.

2025-02-14 08:00 UTC, closed without merging