Personal item loadouts
Sector-Umbra/Sector-Umbra pull request #26
Opened 2024-04-27 21:14 UTC by arimah

## About the PR
Adds personal items as a new category in the loadouts setup.

## Why / Balance
We have a variety of personal items, which currently can't be selected by their rightful owners in any way. I understand most sessions start with a flurry of ahelps along the lines of "hey, can I have item X?". Now that loadouts are available, we can add personal items to the loadout setup. With this implementation, personal items are locked based on the character name (exact match, including letter case!).

## Technical details
This PR touches C# in order to accomplish the following:
- Add a new `LoadoutEffect` named `PersonalItemLoadoutEffect`, responsible for checking whether an item is allowed to be selected. Loadout effects are usually used to restrict items by job playtime, but here we use it to restrict items by character name.
- Rather unfortunately, with upstream's implementation, there is *no way* to get the character name from inside `LoadoutEffect.Validate()`. I had to go and add an `ICharacterProfile` parameter, and update every single place `Validate()` is called, which turned out to be a bigger change than I would have liked.

YAML changes amount to:
- Add `loadout`s and `startingGear` for all personal items currently in Umbra.
- Add three new `loadoutGroup`s: `PersonalItemsJobAgnostic` contains all unrestricted personal items, `PersonalItemsHoS` for the Head of Security (includes job-agnostic items and "moonlit coat"), and `PersonalItemsDetective` for the Detective (includes job-agnostic items and "moonlit holster")
- Add the new loadout groups to every job, including those from CD, except Prisoner. As far as I can tell, there is no way to add loadout groups outside of modifying the `roleLoadout` directly.

TODO: Probably make the character name matcher case-insensitive.

## Media
Janitor loadout for Wipes-the-Floor:
![image](https://github.com/Sector-Umbra/Sector-Umbra/assets/30327355/59560d3c-ef6e-4bf4-940f-a0d703c93406)

Librarian loadout for Really-Likes-Reading:
![image](https://github.com/Sector-Umbra/Sector-Umbra/assets/30327355/65664bf2-14c1-47c0-98d5-a13332ae3e72)
Note the tooltip that explains why the Maple Moondancer plushie is unavailable.

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
I sure hope not. But future upstream changes to loadouts will almost certainly break our code here.

**Changelog**
:cl:
- add: Personal items can now be selected from the loadout screen. No need to ahelp anymore!

2024-04-28 02:32 UTC, FlannelVioiln requested changes

2024-04-28 02:32 UTC, FlannelVioiln commented on Content.Shared/Preferences/Loadouts/Effects/PersonalItemLoadoutEffect.cs
> +            humanoid.Name.Equals(CharacterName, StringComparison.InvariantCultureIgnoreCase))
I would suggest also removing special characters and white space. While what you have inputed for current personal items looks great! removing special characters helps to future proof. For example would catch Frostbite-Drago / Frostbite Drago mismatches

2024-04-28 10:19 UTC, arimah commented on Content.Shared/Preferences/Loadouts/Effects/PersonalItemLoadoutEffect.cs
> +            humanoid.Name.Equals(CharacterName, StringComparison.InvariantCultureIgnoreCase))
I specifically chose _not_ to implement anything like this, because:

1. The game trims leading and trailing white space from the name when saving it. Though it performs no normalization of internal white space (e.g. collapsing repeated spaces to a single space), such issues are not common and not _generally_ hard to fix as a player.
2. "Special character" is a poorly defined category subject to interpretation.
3. Punctuation is _part of the name_. I don't think `Frostbite-Drago` and `Frostbite Drago` _should_ be considered the same, because they aren't! Considering these items are meant to be strictly personal, I'd prefer to err on the side of caution and not allow two _similarly_-named characters to have the same item.

I hope that makes sense. :)

2024-05-01 15:25 UTC, arimah commented
We've had a few changes to personal items, and there's a pending upstream merge. I'm marking this as draft until I'm able to bring it up to date. :)

2024-05-10 11:49 UTC, TsjipTsjip approved these changes
Works on my machine. Bonus points for validation of the loadout on spawning, as a selected loadout item disables when you change your name from the required name. This will significantly decrease admin burden.

2024-05-10 11:58 UTC, merged