adds clouds and duck poster (by kezu)
Sector-Umbra/Sector-Umbra pull request #3
Opened 2024-04-02 13:57 UTC by Aexxie

## About the PR

added two new posters
## Why / Balance

## Technical details

## Media

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

2024-04-05 09:21 UTC, arimah requested changes
This PR would benefit from a screenshot showing what these new posters look like in game.

2024-04-05 09:21 UTC, arimah commented on Resources/Prototypes/_Umbra/Entities/Structures/Wallmounts/posters.yml
> +  parent: BaseSign
Extend `BasePoster` instead and you get `WallMount` and `Destructible` components for free, whilst ensuring consistency with existing posters present and future. Then all you need to override is the sprite path. :)

2024-04-05 13:55 UTC, Aexxie commented on Resources/Prototypes/_Umbra/Entities/Structures/Wallmounts/posters.yml
> +  parent: BaseSign
Pretty sure that it errors whenever you have any "duplicate" component variables - including sprite comp. I will try it later, but the reason `BasePoster` works is due to the fact that it's sprite path is set to a single RSI file in which all poster sprites are stored.

2024-04-05 13:56 UTC, Aexxie commented
> This PR would benefit from a screenshot showing what these new posters look like in game.

Will fix this later. Must've forgotten to initially.

2024-04-05 14:04 UTC, arimah commented on Resources/Prototypes/_Umbra/Entities/Structures/Wallmounts/posters.yml
> +  parent: BaseSign
Component definitions in prototypes are merged together by type. That's how the posters that derive from `UmbraPosterBase` can have their own `Sprite` component that overrides only the `state` (and all other top-level properties are unmodified).

I must correct myself, though: the base poster is called `PosterBase`, and not at all `BasePoster` as I wrote initially. I got things mixed up with `BaseSign`, oops.

2024-04-05 15:00 UTC, Aexxie commented on Resources/Prototypes/_Umbra/Entities/Structures/Wallmounts/posters.yml
> +  parent: BaseSign
You were right about sprite comp, I think it might just be other components that throw an error.

2024-05-15 18:22 UTC, Necro-a commented
is this ever gonna make it in or stay permanently as a PR?

2024-05-15 18:25 UTC, TsjipTsjip commented
Still on the planning as "Need to recreate this PR at some point", keeping it open so it stays in my field of view until I get around to this.

2024-05-31 09:38 UTC, TsjipTsjip commented
Superceded by #60 .

2024-05-31 09:38 UTC, closed without merging