Add Welds' RIG
Sector-Umbra/Sector-Umbra pull request #33
Opened 2024-05-03 08:47 UTC by KittenColony

## About the PR
Adds a personal item for Welds, specifically the RIG they have had in their description for _months_

## Why / Balance
Welds is can walk!

## Technical details
Sprites and YAML

## Media
![image](https://github.com/Sector-Umbra/Sector-Umbra/assets/149278380/c2c71b5b-5fe2-4aa1-bd1c-71b674d1e38b)
![image](https://github.com/Sector-Umbra/Sector-Umbra/assets/149278380/dcc6838b-05a2-42a6-b4a7-f9a46cb84f33)![image](https://github.com/Sector-Umbra/Sector-Umbra/assets/149278380/11f46442-c6f7-4992-a5e7-34a8a6bc25e9)

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

nuh uh

**Changelog**

:cl:

* add: Welds' RIG

2024-05-03 08:55 UTC, TsjipTsjip commented
At a glance on my phone, this looks okay. Will test properly this weekend.

2024-05-03 09:25 UTC, Simyon264 commented
Looks all good, will have to test ingame once I'm home.

2024-05-03 13:37 UTC, Simyon264 approved these changes
![image](https://github.com/Sector-Umbra/Sector-Umbra/assets/63975668/67f6b995-9cb8-4316-afd2-f77a562b831f)

It works ingame. One small nitpick which is not that important: The footstep sounds have a weird echo that you would expect from maints, not in a hallway. But that is not very noticable.

2024-05-10 08:10 UTC, TsjipTsjip requested changes
GM approval, but one comment that needs to be addressed before this can be merged. I was not given write access to the branch to resolve this myself.

2024-05-10 08:49 UTC, TsjipTsjip requested changes
Guh! I didn't click save on the comment!

2024-05-10 08:49 UTC, TsjipTsjip commented on Resources/Prototypes/_Umbra/Entities/Clothing/Shoes/misc.yml
> +  description: Made from an ATMOS hardsuit and a pair of Magboots. You don't know how, but it has gyroscoptic capabilities. No wonder They're still here.
What's going on with the capital T in the last sentence? Is this intentional?

2024-05-10 10:42 UTC, KittenColony commented on Resources/Prototypes/_Umbra/Entities/Clothing/Shoes/misc.yml
> +  description: Made from an ATMOS hardsuit and a pair of Magboots. You don't know how, but it has gyroscoptic capabilities. No wonder They're still here.
Welds is non-binary, same logic behind H(e) S(he), dunno if its correct though

2024-05-10 11:39 UTC, TsjipTsjip commented on Resources/Prototypes/_Umbra/Entities/Clothing/Shoes/misc.yml
> +  description: Made from an ATMOS hardsuit and a pair of Magboots. You don't know how, but it has gyroscoptic capabilities. No wonder They're still here.
Fair, but that wasn't the issue I wanted to point out. Personal pronouns generally shouldn't be capitalized, I was wondering if there was a reason for that here.

2024-05-10 17:13 UTC, KittenColony commented on Resources/Prototypes/_Umbra/Entities/Clothing/Shoes/misc.yml
> +  description: Made from an ATMOS hardsuit and a pair of Magboots. You don't know how, but it has gyroscoptic capabilities. No wonder They're still here.
in that case this is incorrect then

2024-05-15 16:58 UTC, arimah requested changes

2024-05-15 16:58 UTC, arimah commented on Resources/Prototypes/_Umbra/Loadouts/Miscellaneous/personal_items.yml
> +    - ClothingShoesMiscWeldsWalker
In addition to this (which is all correct), the item must _also_ be added to every applicable `loadoutGroup` defined in `Resources/Prototypes/_Umbra/Loadouts/loadout_groups.yml`. Each job has a set of loadout groups, each loadout group has a set of loadouts, each loadout has a starting gear (equipment), each starting gear assigns items... Yes, the loadouts system is a mess.

2024-05-15 16:59 UTC, TsjipTsjip commented on Resources/Prototypes/_Umbra/Loadouts/Miscellaneous/personal_items.yml
> +    - ClothingShoesMiscWeldsWalker
Awww man.... I'm not even done screaming at dotnet yet and you're giving me this?

This is my bad. I'll resolve this in a bit.

2024-05-15 17:02 UTC, TsjipTsjip commented on Resources/Prototypes/_Umbra/Loadouts/Miscellaneous/personal_items.yml
> +    - ClothingShoesMiscWeldsWalker
Resolved by 470e983 .

2024-05-15 17:20 UTC, TsjipTsjip commented
Still needs testing in-game and then this is good to ship.

2024-05-17 06:48 UTC, merged