Necroas small salvage update.
Sector-Umbra/Sector-Umbra pull request #38
Opened 2024-05-10 17:59 UTC by Necro-a

## About the PR
 Added a new Salvage facility: Geneticore, for the Shadow biome, as well as 2 new enemy types, Flesh and Elementals. Also added more drops to the expedition table. I also switched the Shadow biomes chasms for shadow anomaly shadows.

## Why / Balance
 I have always felt like salvage expeditions needed more variety and more exciting loot.

## Technical details

Negative, sir.
## Media

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

Added Geneticore facility
Reworked the shadow biome by replacing the chasms with shadow anomaly shadows
Added more expedition drops
Added Ore crabs and Flesh monsters to expedition enemy types.

2024-05-10 18:09 UTC, Simyon264 commented
Could you please post screenshots of the additions?

2024-05-10 18:24 UTC, Necro-a commented
> Could you please post screenshots of the additions?

Is that good?

2024-05-10 18:43 UTC, Necro-a commented
Also, small note, this is the first time im doing something like this, keep that in mind

2024-05-11 07:20 UTC, TsjipTsjip commented
Something about this pull request is upsetting the linter. I'll have to poke around with the PR to see what exactly is going on.

2024-05-13 16:47 UTC, Kukutis96513 commented
how rare is this facility anyway? looking at the screenshots theres alot of loot in it.

2024-05-14 19:36 UTC, Necro-a commented
> Something about this pull request is upsetting the linter. I'll have to poke around with the PR to see what exactly is going on.

Fixed it, added the tag needed.

2024-05-17 06:59 UTC, TsjipTsjip requested changes
Lots of the same stuff. Have not tested this in-game yet. (How-to-test steps would be appreciated.)

2024-05-17 06:59 UTC, TsjipTsjip commented on Resources/Maps/Dungeon/geneticore.yml
Should be in the _Umbra namespace.

2024-05-17 06:59 UTC, TsjipTsjip commented on Resources/Prototypes/Entities/Mobs/NPCs/flesh.yml
Should be added in a new file in the _Umbra namespace.

2024-05-17 06:59 UTC, TsjipTsjip commented on Resources/Prototypes/Procedural/Themes/geneticore.yml
Should be in the _Umbra namespace.

2024-05-17 06:59 UTC, TsjipTsjip commented on Resources/Prototypes/Procedural/biome_templates.yml
What do these changes do in-game? This looks like it affects things outside of the salvage dungeon being added.

2024-05-17 06:59 UTC, TsjipTsjip commented on Resources/Prototypes/Procedural/dungeon_configs.yml
Should be added in a new file in the _Umbra namespace.

2024-05-17 06:59 UTC, TsjipTsjip commented on Resources/Prototypes/Procedural/salvage_loot.yml
Umbra comment implies only WeaponCrusher was added. Put Umbra comments on everything, or make it clear by stating `# START OF UMBRA ADDITIONS` and `# END OF UMBRA ADDITIONS` around the entire modified block.

This is gonna really really need a big balancing consideration as this also impacts other dungeons. I'm not sure I like this at first glance but we'll see how we go along.

2024-05-17 06:59 UTC, TsjipTsjip commented on Resources/Prototypes/Procedural/salvage_mods.yml
Separate file in _Umbra namespace, or Umbra comments.

2024-05-17 06:59 UTC, TsjipTsjip commented on Resources/Prototypes/tags.yml
No clue what this does, not my expertise, needs an _Umbra namespaced file tho.

2024-05-17 06:59 UTC, TsjipTsjip commented on Resources/Prototypes/Procedural/salvage_factions.yml
_Umbra namespace please.

2024-05-17 07:04 UTC, Necro-a commented on Resources/Prototypes/Procedural/biome_templates.yml
In game, all this does is replace the shadow biomes chasms with shadow kudzu shadows. i found it alot more fitting and less annoying to play. Granted this does affect the biome outside of expeditions as well but you can at least admeme using it without worrying about people getting round removed due to lag and stuff.

2024-05-17 07:13 UTC, Necro-a commented
> Lots of the same stuff. Have not tested this in-game yet. (How-to-test steps would be appreciated.)

I believe it should be as easy as putting the geneticore atlas in maps/dungeon and the other geneticore.yml file in procedural/themes, then running the dungen command.

2024-05-17 07:16 UTC, TsjipTsjip commented
> I believe it should be as easy as putting the geneticore atlas in maps/dungeon and the other geneticore.yml file in procedural/themes, then running the dungen command.

I am not a salvager. I have not played salvage since months ago. Tell me how to test this biome in-game, what do I need to do in-game to test it.

2024-05-17 07:28 UTC, Necro-a commented
> > I believe it should be as easy as putting the geneticore atlas in maps/dungeon and the other geneticore.yml file in procedural/themes, then running the dungen command.
> 
> I am not a salvager. I have not played salvage since months ago. Tell me how to test this biome in-game, what do I need to do in-game to test it.

As in, doing an actual ingame expedition?

2024-05-17 18:12 UTC, Necro-a commented
> > I believe it should be as easy as putting the geneticore atlas in maps/dungeon and the other geneticore.yml file in procedural/themes, then running the dungen command.
> 
> I am not a salvager. I have not played salvage since months ago. Tell me how to test this biome in-game, what do I need to do in-game to test it.

1) Download the following: 
/Maps/_Umbra/Dungeon/geneticore.yml 
/Prototypes/_Umbra/Procedural/Themes/geneticore.yml
/Prototypes/_Umbra/Procedural/dungeon_configs.yml
/Prototypes/_Umbra/Procedural/salvage_mods.yml
/Prototypes/_Umbra/tags.yml

2) Put the files in the appropriate areas. (Aka just copy the file paths for the folders

3) Edit biome_templates.yml the same way its changed in the commits

4) Load the game up, spawn an expedition console, pick a shadow biome expedition.

5) Give yourself whatever gear you deem appropriate for a salvager to have, spawn a reclaimer (or any shuttle that can FTL.) and FTL to the expedition and play through it

Hope that helps.

2024-05-18 08:07 UTC, TsjipTsjip commented
Okay I didn't mean *that* in depth. What I wanted to know is if there's a way to force an expedition to generate with these settings, rather than having to get lucky on the expeditions console. (Far as I understand it, even shadow biome could be the regular shadow biome and thus not your facility.) I'll see if I can review this throughout next week. Timeline for merge is probably gonna be next sunday if no more major issues are found.

2024-05-18 08:10 UTC, TsjipTsjip requested changes
More minor remarks, this is already ready for full review tho. I'm gonna see if I can get that done throughout the following week.

2024-05-18 08:10 UTC, TsjipTsjip commented on Resources/Prototypes/Procedural/salvage_mods.yml
> +
This file should be left unchanged.

2024-05-18 08:10 UTC, TsjipTsjip commented on Resources/Prototypes/Procedural/biome_templates.yml
> +      threshold: 0.5
Add a `# Umbra` comment.

2024-05-18 08:10 UTC, TsjipTsjip commented on Resources/Prototypes/Procedural/biome_templates.yml
> +      - ShadowKudzuWeak
Add a `# Umbra` comment.

2024-05-18 09:00 UTC, Necro-a commented
> Okay I didn't mean _that_ in depth. What I wanted to know is if there's a way to force an expedition to generate with these settings, rather than having to get lucky on the expeditions console. (Far as I understand it, even shadow biome could be the regular shadow biome and thus not your facility.) I'll see if I can review this throughout next week. Timeline for merge is probably gonna be next sunday if no more major issues are found.

You can forcefully generate a _dungeon_ but an entire expedition im not sure. Also, no worries, it should always generate a facility no matter what. If you wanna make sure you don't have to be lucky with the expedition console you can try removing the biome mods and dungeon mods from salvage_mods.yml so it ONLY shows the shadow biome.

2024-06-09 16:28 UTC, SlamBamActionman commented
Tested ingame and it seems to run just fine. 👍👍

There's probably something to be said about how the Elemental category is a pretty weak enemy type (especially since Salvage is the one job fully equipped to deal with ore crabs), but other than that it seems coolio.

2024-06-10 09:29 UTC, Necro-a commented
> Tested ingame and it seems to run just fine. 👍👍
> 
> There's probably something to be said about how the Elemental category is a pretty weak enemy type (especially since Salvage is the one job fully equipped to deal with ore crabs), but other than that it seems coolio.

Understood. Should i maybe add a salvage version of the ore crabs that are a bit stronger? Or maybe add specific types of reagent slimes to it so it matches in difficulty with the other enemy types?

2024-06-16 05:22 UTC, TsjipTsjip commented
Will have a proper look at this soon.

2024-07-18 20:59 UTC, luckyshotpictures approved these changes
Requested changes have been provided. Good to merge.

2024-08-04 19:41 UTC, TsjipTsjip approved these changes
Works in-game, drops were fixed. Sure, let's do this.

2024-08-04 19:42 UTC, merged