adds clouds and duck poster (by kezu)
Sector-Umbra/Sector-Umbra pull request #60
Opened 2024-05-31 09:38 UTC by TsjipTsjip

## About the PR

Adds two new posters, supercedes #3 .

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

![image](https://github.com/Sector-Umbra/Sector-Umbra/assets/19798667/9311796b-07b7-4860-a628-ca2cc1f0cb89)

**Changelog**

Nope.

2024-05-31 11:08 UTC, arimah requested changes
Works as intended, including the slightly creepy animation. :)

I understand from maintainer discussions that the poster is not intended to be part of the random poster pool. If that's the case, nothing needs to change in that regard.

2024-05-31 11:08 UTC, arimah commented on Resources/Prototypes/_Umbra/Entities/Structures/Wallmounts/posters.yml
> +        offset: 0
I'm not a huge fan of how these components are copied from `PosterBase`. I think it would be preferable to extend that component and only override the sprite path, as that's the only thing that's different.

2024-05-31 11:35 UTC, TsjipTsjip commented on Resources/Prototypes/_Umbra/Entities/Structures/Wallmounts/posters.yml
> +        offset: 0
Resolved by 510fb11 . Both poster definitions now mirror how upstream's posters are defined.

2024-06-01 12:12 UTC, arimah approved these changes

2024-06-01 12:12 UTC, merged