Xeno Station - Beta v1 version
Sector-Umbra/Sector-Umbra pull request #64
Opened 2024-06-07 21:37 UTC by SlamBamActionman

## About the PR

This PR adds a playtest version of the Xeno station - an alien-themed station map for 15-60 players. It features new cosmetic walls, flooring and items, as well as minor changes to existing prototypes to make the map appear correctly.

This is the Beta v1 version - it should be possible to hold full playable shifts on it, but it has not yet been tested in all scenarios and jobs in a live environment. This PR should be reverted after the playtest has concluded.

## Technical details

Added content:
- Xeno map
- Xeno cargo shuttle
- Xeno floor & Dark techmaint floor (uncraftable)
- Chitin wall & Reinforced chitin (reskin of solid wall/reinforced wall, uncraftable, deconstructs into girders)
- Alien air alarm & alien fire alarm (reskins, uncraftable)
- Rusted thruster (pointless cosmetic structure)

Mapping content:
- Blood & Flurosulfuric Acid puddles
- Xeno Queen spawner
- Spent pistol cartridge prototype

Changes:
- Shuttle wall; reparented to remove "rusted reinforced wall" replacement component (this shouldn't even be a thing in upstream, it's just a byproduct of no map using shuttle walls so no one has ever noticed it)

Known issues:
- The map gets the error "Error in map file: found local entity UID '0' which does not exist." due to incorrectly set device linking. Map still runs fine.
- Shuttle walls _on the station_ can get replaced with rusted solid walls.
- Brig sleeping gas atmos setup isn't functional

## Media

![image](https://github.com/Sector-Umbra/Sector-Umbra/assets/83650252/0c429e64-308d-4b1d-9d9a-7607af2d22e1)

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

2024-06-08 08:28 UTC, TsjipTsjip requested changes
Everything should be Umbra namespaced. We can revert this PR when we merge the upstream batch that includes this map when that time comes.

2024-06-08 08:28 UTC, TsjipTsjip commented on Content.IntegrationTests/Tests/PostMapInitTest.cs
> +            "Xeno"
Should be added to the `GameMaps` array instead.

2024-06-08 08:28 UTC, TsjipTsjip commented on Resources/Prototypes/Maps/xeno.yml
> +            TechnicalAssistant: [ 3, 3 ]
`SeniorEngineer` is missing.

2024-06-08 08:28 UTC, TsjipTsjip commented on Resources/Prototypes/Maps/xeno.yml
> +            Paramedic: [ 1, 1 ]
`SeniorPhysician` is missing.

2024-06-08 08:28 UTC, TsjipTsjip commented on Resources/Prototypes/Maps/xeno.yml
> +            Borg: [ 2, 2 ]
`SeniorResearcher` is missing.

2024-06-08 08:28 UTC, TsjipTsjip commented on Resources/Prototypes/Maps/xeno.yml
> +            Lawyer: [ 2, 2 ]
`SeniorOfficer` is missing.

2024-06-14 15:08 UTC, TsjipTsjip requested changes
Good to merge when requested changes are addressed. Map loads fine in-game.

2024-06-14 15:08 UTC, TsjipTsjip commented on Resources/Prototypes/Entities/Structures/Walls/walls.yml
This needs comments signifying the change is from Umbra.

2024-06-14 15:08 UTC, TsjipTsjip commented on Resources/Prototypes/Recipes/Construction/Graphs/structures/girder.yml
> +
Large additions like this benefit from `# START OF UMBRA ADDITION` at the start and `# END OF UMBRA ADDITION` at the end, to signify without doubt that the entire section is an umbra modification.

2024-06-14 15:08 UTC, TsjipTsjip commented on Resources/Prototypes/Recipes/Construction/Graphs/structures/girder.yml
> +    # Umbra, Xeno map
OCD triggers here and since I'm making you look at this file anyways, here goes: `Umbra: Xeno map`.

2024-06-14 15:08 UTC, TsjipTsjip commented on Resources/Prototypes/Recipes/Construction/Graphs/structures/girder.yml
> +    # Umbra, Xeno map
Same old.

2024-06-14 15:08 UTC, TsjipTsjip commented on Resources/Prototypes/Entities/Structures/Walls/walls.yml
> +  #Edited to prevent turning into rusted walls on Xeno station
`# Umbra: ...`, and should be on the changed line, not the entire node.

2024-06-14 15:47 UTC, SlamBamActionman commented on Resources/Prototypes/Entities/Structures/Walls/walls.yml
> +  #Edited to prevent turning into rusted walls on Xeno station
The shuttle wall is getting reparented from ReinforcedWall to BaseWall so that the ReinforcedWallReplacementMarker component isn't used, which means it's more than a single line being changed (though the stats are the same). I've kept it located as-is, but updated the description to clarify what was changed.

2024-06-14 15:49 UTC, SlamBamActionman commented
Note: last commit contains a minor addition/bugfix that I had missed to include in the Umbra build
- ShuttleWallInterior has been reparented from WallSolid to BaseWall (in the same way that ShuttleWall was reparented from ReinforcedWall to BaseWall).

2024-06-16 14:59 UTC, TsjipTsjip approved these changes
Approved for playtesting.

2024-06-16 15:00 UTC, merged