Iris Beta Test v0.91
Sector-Umbra/Sector-Umbra pull request #68
Opened 2024-06-15 04:38 UTC by luckyshotpictures

## About the PR

Iris Station, Map rendered soon:tm: after I slept

## Why / Balance

## Technical details

## Media

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

2024-06-16 05:25 UTC, TsjipTsjip requested changes

2024-06-16 05:25 UTC, TsjipTsjip commented on Resources/Maps/_Umbra/Iris.yml
Rename the file to `iris.yml`.

2024-06-16 05:25 UTC, TsjipTsjip commented on Resources/Prototypes/_Umbra/Maps/iris-prototype.yml
Rename the file to `iris.yml`.

2024-06-16 05:25 UTC, TsjipTsjip commented on Resources/Prototypes/_Umbra/Maps/iris-prototype.yml
> +  mapPath: /Maps/_Umbra/Iris.yml
Should be updated if the map file name was updated already too.

2024-06-16 05:25 UTC, TsjipTsjip commented on Resources/Prototypes/_Umbra/Maps/iris-prototype.yml
> +            - Passenger
This no longer exists, instead, define `Passenger` in the list of available jobs with tresholds `-1` and `-1`.

2024-06-16 15:02 UTC, TsjipTsjip approved these changes

2024-06-16 15:02 UTC, TsjipTsjip commented on Resources/Maps/_Umbra/Iris.yml
Rename the file to `iris.yml`, be mindful not to use an uppercase I.

2024-06-16 15:02 UTC, TsjipTsjip submitted a review, later dismissed
I messed up the last one. Treat it as a requested changes.

2024-07-24 08:08 UTC, luckyshotpictures commented
Fuck it, I will be remaking Iris to be better™

2024-08-04 19:51 UTC, closed without merging