Add CVar to disable the shuttle calling the round end timer upon arrival.
Sector-Umbra/Sector-Umbra pull request #72
Opened 2024-06-21 21:20 UTC by Simyon264

## About the PR

Adds a CVar that disables the shuttle calling the 2 minute round end timer.
## Why / Balance

Makes it easier to avoid early round ends via miscommunication. 

## Technical details

Adds a new CVar, a boolean, which is checked when the shuttle enters FTL. If its true, the timer is started and once the shuttle lands, the 2 minutes (or whatever you have set it to) start.

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase
![image](https://github.com/Sector-Umbra/Sector-Umbra/assets/63975668/94ad7b27-3e8e-4fc7-957d-5d40a7eef6cc)

2024-06-23 07:24 UTC, TsjipTsjip requested changes

2024-06-23 07:24 UTC, TsjipTsjip commented on Content.Shared/CCVar/CCVars.cs
> +
Needs` _Umbra` tag. Also the name is not very descriptive, `enable_end_of_round_timer` would be better.

2024-06-30 13:51 UTC, arimah requested changes

2024-06-30 13:51 UTC, arimah commented on Content.Server/_Umbra/Administration/Toolshed/RoundEndShuttleCommand.cs
> +public sealed class RoundEndShuttleCommand : ToolshedCommand
I have to say, I _really_ don't like the name of this command. "roundendshuttle"? What does that even mean? Why not "shuttleroundrestarttimer"? Or... I don't know, something that describes it better.

2024-06-30 13:51 UTC, arimah commented on Resources/Locale/en-US/_Umbra/commands/round-end-shuttle-command.ftl
> +command-description-roundendshuttle-disable = Turns the round end timer off once the shuttle lands. This will not have an affect if the shuttle already launched.
Suggested rewording:
```
command-description-roundendshuttle-enable = Turns on the automatic round restart timer. This will not have an effect if the shuttle has already left the station.
command-description-roundendshuttle-disable = Turns off the automatic round restart timer. This will not have an effect if the shuttle has already left the station.
```

2024-08-03 16:03 UTC, TsjipTsjip commented
@Simyon264 Can you look at the last review and address the comments please?

2024-08-09 15:25 UTC, Simyon264 commented
> @Simyon264 Can you look at the last review and address the comments please?

Working on this now.

2024-09-29 12:21 UTC, closed without merging