New personal items: Borgs-the-Brains beret and scarf
Sector-Umbra/Sector-Umbra pull request #75
Opened 2024-06-30 14:23 UTC by Tych0theSynth

## About the PR
Added new personal items for Borgs-the-Brains: A customised scientific beret and striped purple scarf.

## Why / Balance
She likes to look pretty.

## Technical details
No.

## Media
![2024-06-30 14_48_15-Space Station 14](https://github.com/Sector-Umbra/Sector-Umbra/assets/151581207/0e263bbe-eb22-4318-b0ed-e79c665540fc)
![2024-06-30 14_48_37-Space Station 14](https://github.com/Sector-Umbra/Sector-Umbra/assets/151581207/8ff63a0a-bb59-444f-8e03-3faa421ed859)
![2024-06-30 14_49_19-Space Station 14](https://github.com/Sector-Umbra/Sector-Umbra/assets/151581207/0571c832-a071-433e-9fb2-d6d9897dbde0)
![2024-06-30 14_49_01-Space Station 14](https://github.com/Sector-Umbra/Sector-Umbra/assets/151581207/0d68d44b-6320-4b15-8016-29589a5a1bbd)

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
None!

**Changelog**
Make sure to take this Changelog template out of the comment block in order for it to show up.
:cl:
- add: Added personal items for Borgs-the-Brains.

2024-06-30 15:45 UTC, arimah requested changes

2024-06-30 15:45 UTC, arimah commented on Resources/Prototypes/_Umbra/Entities/Clothing/Head/hats.yml
> +    sprite: _Umbra\Clothing\Head\Hats\borgsberet.rsi
I missed this initially: all paths must use forward slashes :)

2024-07-02 20:03 UTC, TsjipTsjip commented
Looks good at first glance, also no violation of personal item rules. Will test tomorrow.

2024-07-03 15:53 UTC, TsjipTsjip approved these changes

2024-07-03 16:05 UTC, arimah approved these changes

2024-07-03 16:05 UTC, merged