New personal item: Jotty's Pet Rock 'Bobby'
Sector-Umbra/Sector-Umbra pull request #83
Opened 2024-07-05 14:33 UTC by Tych0theSynth

## About the PR
Added a personal item for Joetta-Beedell: Bobby the pet rock. - draft as incomplete at this time

## Why / Balance
On request of @luckyshotpictures. Pet rock. PET. ROCK. IS BOBBY.

## Technical details
Tested and working with loadouts. Tested and working in game. 
Delay between sprite changes to be confirmed prior to commit of the rsi. 

## Media
https://github.com/Sector-Umbra/Sector-Umbra/assets/151581207/a9fc300b-4051-42f5-aef2-360e9d2c12aa

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
I should hope not, unless Jotty throws the rock through a window and kills someone.

**Changelog**
Make sure to take this Changelog template out of the comment block in order for it to show up.
:cl:
- add: Added a pet rock for Jotty.

2024-07-06 06:37 UTC, TsjipTsjip requested changes
One small thing, rest looks good to go.

2024-07-06 06:37 UTC, TsjipTsjip commented on Resources/Textures/_Umbra/Objects/Fun/bobby.rsi/meta.json
> +    "copyright": "Taken from Paradise Station, customised by Tych0theSynth",
This needs an exact commit reference.

2024-07-06 14:25 UTC, Tych0theSynth commented on Resources/Textures/_Umbra/Objects/Fun/bobby.rsi/meta.json
> +    "copyright": "Taken from Paradise Station, customised by Tych0theSynth",
GRAH, the original didn't have one. I'll have to try and find it >.>

2024-07-19 14:28 UTC, TsjipTsjip approved these changes
Bobby.

2024-07-19 14:29 UTC, merged