Remove QSI from Tech Tree
Sector-Umbra/Sector-Umbra pull request #85
Opened 2024-07-07 21:48 UTC by SlamBamActionman

## About the PR

Removes the Quantum Spin Inverter from the Science tech tree, and the honki shuttle. It's only available via admin entity spawn menu.

## Why / Balance

Requested by Game Masters due to bugs.
Note that this makes the Experimental T3 techs only have one option. 

## Technical details

This only comments out the code for where the QSI is accessed in the game, not the prototype itself. 

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

- remove: Removed QSI

2024-07-13 09:52 UTC, TsjipTsjip requested changes

2024-07-13 09:52 UTC, TsjipTsjip commented on Resources/Maps/Shuttles/ShuttleEvent/honki.yml
This should be done through a migration (`Resources/migrations.yml`) instead.

2024-07-19 14:26 UTC, SlamBamActionman commented on Resources/Maps/Shuttles/ShuttleEvent/honki.yml
I've tested this now and unfortunately this does not work with `migrations.yml`. 
The issue is that the Quantum Spin Inverters are inside of a container. If the QSIs are migrated to null, the containers still have the ID entity reference, making them contain a "null object" which throws an error.

With your blessing I can change the QSIs to AI Toys or something similar, though.

2024-07-19 14:31 UTC, TsjipTsjip commented on Resources/Maps/Shuttles/ShuttleEvent/honki.yml
Probably more trouble than it's worth.... Revert the clown shuttle file, as thought NT has stopped QSI research, others could still have a pair realistically.

Good to merge after.

2024-07-19 14:53 UTC, TsjipTsjip approved these changes
Bye bye QSI.

2024-07-19 14:54 UTC, merged