Lizard Scales Gradient Marking
Sector-Umbra/Sector-Umbra pull request #87
Opened 2024-07-12 00:32 UTC by Frostbitey

## About the PR
- Adds the "Gradient Scales" marking.
The marking has been devided to three markings, due to the marking not working properly when put together in to one, If I would've put the whole marking on the character as one, sure it would work. But the leg marking would layer Over the clothing.
I do not know why this was happening, I was troubleshooting with it for a hour and a half straight, but no positive results were observed, hence the Gradient Scales are divided to three markings, The Chest marking, Legs marking and the Feet marking.
They all have been put in the Overlay category
The Chest marking has a transparent-gradient end, so that the colors can also blend in to the actual color of the character, for more beliveable gradient.

There is a known issue though, which I cannot myself solve. The tail sprite is a layer above the right foot's sprite (From the character's perspective). Which I cannot fix myself. It is a issue known for other markings, such as the right foot gauze. 
I hope someone can fix this problem in the future.

## Media
### On the front view, you can see the problem with the right foot sprite. The tail is covering it. Again, I do not know how to fix this.
![image](https://github.com/user-attachments/assets/b6fba799-1a30-4e72-b12f-ea85201a28dc)
![image](https://github.com/user-attachments/assets/42b80f16-ceb2-46e1-9197-5bb6af35f0c6)
![image](https://github.com/user-attachments/assets/049de325-f341-49f9-82e1-31900d10011f)
![image](https://github.com/user-attachments/assets/fdd88931-3290-4eaf-873d-968f58b36e70)

### And of course, the color is fully customizable.
![image](https://github.com/user-attachments/assets/c62644f1-7c08-4540-816b-40b4e40d822e)
The results may vary, color theory would be recommended for better results

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Added the Scales Gradient Marking for Reptilians!

2024-07-12 17:25 UTC, UbaserB commented
Frankly, very cute. Will probably use for my lizard as well, maybe also worth a shot at PRing it mainstream?

2024-07-12 17:28 UTC, Frostbitey commented
> Frankly, very cute. Will probably use for my lizard as well, maybe also worth a shot at PRing it mainstream?

I honestly want to keep it Umbra-only, sorry!

2024-07-12 17:35 UTC, UbaserB commented
> > Frankly, very cute. Will probably use for my lizard as well, maybe also worth a shot at PRing it mainstream?
> 
> I honestly want to keep it Umbra-only, sorry!

Am i allowed to use the idea but make my own sprite for wizden?

2024-07-12 17:39 UTC, Frostbitey commented
> > > Frankly, very cute. Will probably use for my lizard as well, maybe also worth a shot at PRing it mainstream?
> > 
> > I honestly want to keep it Umbra-only, sorry!
> 
> Am i allowed to use the idea but make my own sprite for wizden?

Ehhh.. As said, i prefer to just keep it in Umbra, again sorry

2024-07-16 14:52 UTC, Frostbitey commented
Oh, and yes. Forgot to annouce that I cannot commit any changes until the 25th.

2024-07-19 13:30 UTC, SlamBamActionman requested changes

2024-07-19 13:30 UTC, SlamBamActionman commented on Resources/Textures/_Umbra/Mobs/Customization/chestscalesgradient.rsi/ChestLizardGradientShit.png
Oops, I assume?

2024-07-19 13:30 UTC, SlamBamActionman commented on Resources/Prototypes/_Umbra/Entities/Mobs/Customization/Markings/reptilian.yml
> +  bodyPart: LLeg #<- I am aware that this only selects one leg, but the sprite still works on both of them, If I would to insert "LLeg, Rleg", then the sprite would appear a layer above the clothing.
Based on the way how slimes do gradient legs, it seems like the way to do it would be to separate the legs into a left and right sprite. It means you will have to color each leg individually, but that also allows you to have different colors for each leg. Same for the feet.

You can see how slimes have set it up here: https://github.com/Sector-Umbra/Sector-Umbra/blob/676234a6e610098f9b643b49279818729097d08f/Resources/Prototypes/Entities/Mobs/Customization/Markings/slime.yml#L1

I would suggest copying that system and seeing if it fixes the visuals bug you encountered.

2024-08-16 11:57 UTC, SlamBamActionman commented
Just for the sake of keeping record, the maint team decided that this PR can proceed with the combined markings as submitted (not our fault upstream's layering is cooked). 

Address this review comment for the PR to proceed: https://github.com/Sector-Umbra/Sector-Umbra/pull/87#discussion_r1684351613

2024-08-16 12:42 UTC, Frostbitey commented
I've gotten quite sick of this PR, Not only It was a giant pain in the ass to manage but also I lost all the progress and changes in the GitHub Desktop. Im closing this off once and for all.

2024-08-16 12:42 UTC, closed without merging