Membral wings moth marking
Sector-Umbra/Sector-Umbra pull request #93
Opened 2024-07-15 23:54 UTC by pigeonpeas

## About the PR
Membral wings I PR'd for upstream that sadly got denied.

## Media
![image](https://github.com/user-attachments/assets/5fd0d717-4bac-41e9-94cc-dfdb54723d84)

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Membral moth wings marking

2024-07-15 23:57 UTC, pigeonpeas commented
sorry for the way the changes look, visual studio just HAS to fuck with the spacing when i open in a file in it. It still works, I think.

2024-07-19 13:30 UTC, SlamBamActionman requested changes

2024-07-19 13:30 UTC, SlamBamActionman commented on Resources/Textures/Mobs/Customization/Moth/moth_wings.rsi/meta.json
This formatting should be fixed; I've sent a fixed version on Discord for you, since you mentioned Visual Studio was causing this issue for you. Just commit that and it should be good.

2024-08-03 16:01 UTC, TsjipTsjip commented
Need to test this in-game, can't assess if it works from viewing the code itself.

2024-08-03 21:45 UTC, pigeonpeas commented
> Need to test this in-game, can't assess if it works from viewing the code itself.

i did test it in game to get the screenshot. Should i do it again?

2024-08-09 15:17 UTC, TsjipTsjip approved these changes

2024-08-09 15:17 UTC, merged